Webinar ccm
chocolatey/chocolatey.org pull request #1004
Opened 2020-11-18 16:09 UTC by designxsteph

In this PR: 

* Adds CCM Webinar page
* Updates right side announcement bar with CCM Webinar info
* Updates home page with CCM Webinar info

2020-11-18 16:11 UTC, designxsteph commented
@ferventcoder This is up on test.

Note that the link to the blog post on the home page is referencing the link in [this PR](https://github.com/chocolatey/chocolatey.org/pull/1003) that has not been pulled in yet. Clicking the link now redirects to the blog home page.

2020-11-18 16:27 UTC, ferventcoder requested changes
Looks good, but this file needs the typo in the name fixed: chocolatey/Website/Views/Events/Files/01-05-ChocolateyDeploynentSchedules.md

2020-11-18 16:33 UTC, designxsteph commented
> Looks good, but this file needs the typo in the name fixed: chocolatey/Website/Views/Events/Files/01-05-ChocolateyDeploynentSchedules.md

Oy! This has been fixed.

2020-11-19 00:04 UTC, ferventcoder approved these changes

2020-11-19 00:04 UTC, merged