(GH-937) Update to reCAPTCHA v3
chocolatey/chocolatey.org pull request #938
Opened 2020-08-24 17:10 UTC by designxsteph

In an effort to reduce the amount of spam, reCAPTCHA has been updated
from v2 to v3. If reCAPTCHA returns a score of less than 0.5, it is
determined that this is likely a bot, and the form will not be allowed
to submit and an error message will appear on the form.

Docs:
https://developers.google.com/recaptcha/docs/v3

2020-08-26 14:21 UTC, gep13 requested changes
Just a small question...

2020-08-26 14:21 UTC, gep13 commented on chocolatey/Website/Views/Pages/ContactPartner.cshtml
> +                        <input class="btn btn-primary mt-3 g-recaptcha" data-sitekey="@System.Configuration.ConfigurationManager.AppSettings["reCAPTCHA::PublicKey"]" data-callback="onSubmit" data-bad
@designxsteph should this be `Form_ContactPartner`?  All the other changes match the name of the page.  Doubt that this would break anything, was just thinking from a consistency point of view.

2020-08-26 14:57 UTC, designxsteph commented on chocolatey/Website/Views/Pages/ContactPartner.cshtml
> +                        <input class="btn btn-primary mt-3 g-recaptcha" data-sitekey="@System.Configuration.ConfigurationManager.AppSettings["reCAPTCHA::PublicKey"]" data-callback="onSubmit" data-bad
Good catch, I have removed the extra "s".

2020-08-26 15:08 UTC, ferventcoder commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Please try again later."));
Add this as well:

`Sometimes this misidentifies legitimate requests. If this request is legitimate, please use the chat button you'll find on the [home page](https://chocolatey.org) to reach out to our team.`

2020-08-26 17:01 UTC, designxsteph commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Please try again later."));
@ferventcoder I've tried a few things, but it keeps just printing out like below. I've tried a md link and using an <a> tag:

![spamvalidation](https://user-images.githubusercontent.com/42750725/91333846-c0424a00-e793-11ea-9968-71e3892d514c.png)


Any suggestions?

2020-08-26 17:04 UTC, designxsteph commented
> Noted a small change requested.
> 
> Does changing to recaptcha v3 really only require changing the keys? I didn't see any js/html changes necessary here and wasn't sure if I was missing anything.

The only thing that changes in the html is that I added a `data-action` attribute onto each button. We can then track these actions in the console and see where the most spam is coming from. Everything else is automatically taken care of with the html/js already in place.

2020-08-27 16:05 UTC, designxsteph commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Please try again later."));
With some help from @gep13 this has now been addressed and ready for another review.

2020-08-27 19:40 UTC, ferventcoder commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Sometimes this misidentifies legitimate requests. If this request is legitimate, please use the chat button you'll find on the <a href
Okay this is my bad, I went to verify the front page had the chat and we removed it from there. Perhaps we point to https://chocolatey.org/packages instead?

2020-08-28 12:56 UTC, designxsteph commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Sometimes this misidentifies legitimate requests. If this request is legitimate, please use the chat button you'll find on the <a href
@ferventcoder I did add it to the home page in this commit because I saw it wasn't there too. Maybe makes more sense to add the chat to https://chocolatey.org/contact page?

2020-09-17 22:05 UTC, ferventcoder commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Sometimes this misidentifies legitimate requests. If this request is legitimate, please use the chat button you'll find on the <a href
Link directly to Gitter IM

2020-09-18 12:23 UTC, designxsteph commented on chocolatey/Website/Infrastructure/ValidateFormResponseAttribute.cs
> +                    string.Format("Suspicious behavior detected. Sometimes this misidentifies legitimate requests. If this request is legitimate, please use the chat button you'll find on the <a href
This has been updated!

2020-09-22 14:20 UTC, gep13 approved these changes
LGTM!

2020-09-22 14:20 UTC, merged

2020-09-22 14:21 UTC, gep13 commented
@designxsteph thanks for getting this done!