(GH-972) Implement Chat Feature
chocolatey/chocolatey.org pull request #976
Opened 2020-09-23 14:24 UTC by designxsteph

Implements a chat feature that users can ask/interact with Chocolatey
members about Chocolatey for Business. This is restricted to certain
pages that users might navigate to to find out more about the Business
features Chocolatey offers.

2020-09-23 16:41 UTC, ferventcoder requested changes
See if we can move the main bulk of the function out to a js file, then load that in on bundles.reference. That way we can reduce the amount of duplication across multiple pages.

We can pass the chatbotid into the function once loaded and let it decide if it is null or not, and decide to load up. 

See if we can load it at the bottom as well, it doesn't seem like it needs the priority to load with top scripts.

2020-09-23 19:32 UTC, designxsteph commented
@ferventcoder This has been fixed and new version is up on test now.

2020-09-23 20:17 UTC, gep13 requested changes

2020-09-23 20:17 UTC, gep13 commented on chocolatey/Website/Scripts/chat/chat.js
> +    !function () {
@designxsteph should there still be a check in here to verify that the chatBotId isn't null, before attempting to use it?

2020-09-23 20:28 UTC, designxsteph commented on chocolatey/Website/Scripts/chat/chat.js
> +    !function () {
@gep13 Ah yeah, I added that in!

2020-09-25 20:33 UTC, designxsteph commented
@ferventcoder this should be on all the pages we want it on now, let me know if there are more. A new version of this is on test.

2020-09-28 21:40 UTC, ferventcoder approved these changes

2020-09-28 21:40 UTC, merged